version: '3.8'

services:
  playwright:
    build:
      context: ..
      dockerfile: ./.playwright/Dockerfile
    depends_on:
      - myapp
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    network_mode: service:db

  myapp:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      target: dev
    depends_on:
      - db
    command: bash -c "source cs-env/bin/activate; npm run start-app"
    network_mode: service:db

    environment:
      DATASTORE_PROJECT_ID: cr-status-staging
      DATASTORE_EMULATOR_HOST: localhost:15606
