version: '3.8'

services:
  playwright:
    build:
      context: ..
      dockerfile: ./.playwright/Dockerfile
    depends_on:
      - myapp
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    network_mode: host
    volumes:
      - ../client-src/elements/__screenshots__:/work/client-src/elements/__screenshots__
      - ../test-results:/work/test-results

  myapp:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      target: dev
    depends_on:
      - mydb
    command: bash -c "source cs-env/bin/activate; npm run start-app"
    network_mode: host

    environment:
      DATASTORE_PROJECT_ID: cr-status-staging
      DATASTORE_EMULATOR_HOST: localhost:15606
  mydb:
    extends:
      file: ../.devcontainer/docker-compose.yml
      service: db
    network_mode: host
