name: Playwright Tests
on:
  push:
    branches-ignore:
      - "dependabot/**"
      - "daily-test-sync"

jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        # Steps for Playwright testing with container
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Run your tests
          run: npm run pwtests
